"""Central configuration module for TrafficIQ."""

from pathlib import Path

# Base Paths
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
UPLOAD_DIR = DATA_DIR / "raw"
LOGS_DIR = DATA_DIR / "logs"
MODELS_DIR = DATA_DIR / "models"
PROCESSED_DIR = DATA_DIR / "processed"

# Log Filenames
VEHICLE_DETECTIONS_LOG = "vehicle_detections.csv"
EMERGENCY_DETECTIONS_LOG = "emergency_detections.csv"
DENSITY_ANALYSIS_LOG = "density_analysis.csv"
CONGESTION_ANALYSIS_LOG = "congestion_analysis.csv"
PRIORITY_ACTIONS_LOG = "priority_actions.csv"

# Log Absolute Paths
VEHICLE_DETECTIONS_PATH = LOGS_DIR / VEHICLE_DETECTIONS_LOG
EMERGENCY_DETECTIONS_PATH = LOGS_DIR / EMERGENCY_DETECTIONS_LOG
DENSITY_ANALYSIS_PATH = LOGS_DIR / DENSITY_ANALYSIS_LOG
CONGESTION_ANALYSIS_PATH = LOGS_DIR / CONGESTION_ANALYSIS_LOG
PRIORITY_ACTIONS_PATH = LOGS_DIR / PRIORITY_ACTIONS_LOG

# Model Names and Paths
YOLO_MODEL_NAME = "yolov8n.pt"
AMBULANCE_MODEL_FILENAME = "ambulance_detector.pt"
AMBULANCE_MODEL_PATH = MODELS_DIR / AMBULANCE_MODEL_FILENAME
CONGESTION_PREDICTOR_FILENAME = "congestion_predictor.pkl"
CONGESTION_PREDICTOR_PATH = MODELS_DIR / CONGESTION_PREDICTOR_FILENAME

# Model Confidence Defaults
DEFAULT_VEHICLE_CONFIDENCE = 0.35
DEFAULT_AMBULANCE_CONFIDENCE = 0.35

# Application Constants
CONGESTION_LEVELS = ["LOW_CONGESTION", "MEDIUM_CONGESTION", "HIGH_CONGESTION"]
RECOMMENDATION_ACTIONS = ["NORMAL_OPERATION", "EXTEND_GREEN", "HIGH_TRAFFIC_WARNING", "EMERGENCY_PRIORITY"]

# Dashboard Constants
CONGESTION_LEVELS_FILTER = ["ALL"] + CONGESTION_LEVELS
RECOMMENDATION_ACTIONS_FILTER = ["ALL"] + RECOMMENDATION_ACTIONS
